# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["paul.roberts@theguardian.com"]
description = "testing the viability of dictionaries"
language = "assemblyscript"
manifest_version = 2
name = "metering-at-edge-test"
service_id = "5yAc3QZNZQ0AxBfjeMJTjk"

[local_server.dictionaries.metering_test_members_ex]
file = "local_dict.json"
format = "json"
